version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: wavtopia
      POSTGRES_PASSWORD: wavtopia
      POSTGRES_DB: wavtopia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: wavtopia
      MINIO_ROOT_PASSWORD: wavtopia123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  media:
    build:
      context: ./packages/media
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=wavtopia
      - MINIO_SECRET_KEY=wavtopia123
    volumes:
      - media_tmp:/tmp
    depends_on:
      - minio

volumes:
  postgres_data:
  minio_data:
  media_tmp:
