version: "3.8"

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES_BASE}/wavtopia_postgres_data/_data

  minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES_BASE}/wavtopia_minio_data/_data

  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES_BASE}/wavtopia_redis_data/_data

  temp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUMES_BASE}/wavtopia_temp_files/_data
