services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: wavtopia
      POSTGRES_PASSWORD: wavtopia
      POSTGRES_DB: wavtopia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: wavtopia
      MINIO_ROOT_PASSWORD: wavtopia123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  media:
    profiles:
      - production
    build:
      context: .
      dockerfile: packages/media/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - media_tmp:/tmp
    depends_on:
      - minio
      - redis

volumes:
  postgres_data:
  minio_data:
  redis_data:
  media_tmp:
